apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
          - containerPort: 3306
            name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
          - name: MYSQL_DATABASE
            value: phonebook
          - name: MYSQL_PASSWORD
            value: "12345"
          - name: MYSQL_USER
            value: admin
        volumeMounts:
          - name: mysql-pv
            mountPath: /var/lib/mysql